version: "3.8"
services:
  api-gateway:
    build: ./backend/api_gateway
    container_name: api-gateway
    ports:
      - "8090:8090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - foodfast-net

  eureka-server:
    build: ./backend/eureka_server
    container_name: eureka-server
    restart: always
    ports:
      - "8761:8761"
    networks:
      - foodfast-net

  user-service:
    build: ./backend/user_service
    container_name: user-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://foodfast:foodfast456@foodfast.ekg6ihg.mongodb.net/user_db?retryWrites=true&w=majority
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - foodfast-net

  product-service:
    build: ./backend/product_service
    container_name: product-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://foodfast:foodfast456@foodfast.ekg6ihg.mongodb.net/product_db?retryWrites=true&w=majority
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - foodfast-net

  order-service:
    build: ./backend/order_service
    container_name: order-service
    restart: always
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://foodfast:foodfast456@foodfast.ekg6ihg.mongodb.net/order_db?retryWrites=true&w=majority
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - foodfast-net

  payment-service:
    build: ./backend/payment_service
    container_name: payment-service
    restart: always
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://foodfast:foodfast456@foodfast.ekg6ihg.mongodb.net/payment_db?retryWrites=true&w=majority
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - foodfast-net

  cart-service:
    build: ./backend/cart_service
    container_name: cart-service
    restart: always
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://foodfast:foodfast456@foodfast.ekg6ihg.mongodb.net/cart_db?retryWrites=true&w=majority
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - foodfast-net

  drone-service:
    build: ./backend/drone_service
    container_name: drone-service
    restart: always
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://foodfast:foodfast456@foodfast.ekg6ihg.mongodb.net/drone_db?retryWrites=true&w=majority
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - foodfast-net

  delivery-service:
    build: ./backend/delivery_service
    container_name: delivery-service
    restart: always
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://foodfast:foodfast456@foodfast.ekg6ihg.mongodb.net/delivery_db?retryWrites=true&w=majority
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - foodfast-net

  restaurant-service:
    build: ./backend/restaurant_service
    container_name: restaurant-service
    restart: always
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://foodfast:foodfast456@foodfast.ekg6ihg.mongodb.net/restaurant_db?retryWrites=true&w=majority
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_started
    networks:
      - foodfast-net

volumes:
  mongo-data:

networks:
  foodfast-net:
    driver: bridge
