name: CI/CD Pipeline

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build Eureka Server
        working-directory: ./backend/eureka_server
        run: mvn clean install -DskipTests

      - name: Build Product Service
        working-directory: ./backend/product_service
        run: mvn clean install -DskipTests

      - name: Build Order Service
        working-directory: ./backend/order_service
        run: mvn clean install -DskipTests

      - name: Build Payment Service
        working-directory: ./backend/payment_service
        run: mvn clean install -DskipTests

      - name: Build User Service
        working-directory: ./backend/user_service
        run: mvn clean install -DskipTests

      - name: Build Cart Service
        working-directory: ./backend/cart_service
        run: mvn clean install -DskipTests

      - name: Build Drone Service
        working-directory: ./backend/drone_service
        run: mvn clean install -DskipTests

      - name: Build Delivery Service
        working-directory: ./backend/delivery_service
        run: mvn clean install -DskipTests
