name: Project CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

jobs:
  product-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Run tests for product service
        run: mvn test
        working-directory: ./product_service

      - name: Build product service
        run: mvn clean compile
        working-directory: ./product_service

  user-service:
    runs-on: ubuntu-latest
    needs: product-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Run tests for user service
        run: mvn test
        working-directory: ./user_service

      - name: Build user service
        run: mvn clean compile
        working-directory: ./user_service

  order-service:
    runs-on: ubuntu-latest
    needs: user-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Run tests for order service
        run: mvn test
        working-directory: ./order_service

      - name: Build order service
        run: mvn clean compile
        working-directory: ./order_service

 order-service:
    runs-on: ubuntu-latest
    needs: order-service
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "maven"

      - name: Run tests for payment service
        run: mvn test
        working-directory: ./payment_service

      - name: Build payment service
        run: mvn clean compile
        working-directory: ./payment_service